name: localization_ui_tool
description: ui tool for arb localization.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^16.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  file_picker: ^10.2.0
  path: ^1.9.0
  flex_color_scheme: ^8.2.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  build_runner: ^2.4.11
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    - assets/launcher_icon/


flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/launcher_icon/icon.png"
  windows:
    generate: true
    image_path: "assets/launcher_icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/launcher_icon/icon.png"
  linux:
    generate: true
    image_path: "assets/launcher_icon/icon.png"